### ISSUE TITLE
Data attribution

### ISSUE THREAD

**Issue by lucasrodes** [bing-he/Subnational-COVID-19-vaccination#1]
Hi!
Thanks for sharing your plots, it all looks really nice 😄 !

I have noticed that you may be using the data from https://github.com/sociepy/covid19-vaccination-subnational. I think it could be great if you could reference their work in your README or somewhere in the repo. This way, people can trace back the source of your data, and maintainers of the aforementioned project are aware of its usage.

Best

**Comment by bing-he** [comment]
Hi!
Thanks for your reminder.
Right! The reference is very important!

Best,
Bing

**Comment by lucasrodes** [comment]
Your visualizations might be really useful to detect eventual bugs in the data generation. So, once again, thanks for your work.
